bookapp/book/models.py
# Entity

from book import db

from sqlalchemy import text


class Book(db.Model):
    code = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)  # text
    author = db.Column(db.String(50), nullable=False)  # text
    price = db.Column(db.Integer, nullable=False)  # text
    description = db.Column(db.Text())  # textarea
    created = db.Column(db.DateTime(), nullable=False)


# 사용자
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), nullable=False)  # text
    password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), nullable=False, unique=True)

bookapp/book/forms.py
# DTO 역할

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, IntegerField, PasswordField, EmailField
from wtforms.validators import DataRequired, Email, EqualTo, Length


class BookForm(FlaskForm):
    code = IntegerField("도서코드")
    title = StringField("도서명", validators=[DataRequired("title 필수입력")])
    author = StringField("작가명", validators=[DataRequired("author 필수입력")])
    price = IntegerField("가격", validators=[DataRequired("price 필수입력")])
    description = TextAreaField()


# 사용자
class UserForm(FlaskForm):
    username = StringField(
        "아이디",
        validators=[
            DataRequired("아이디 필수입력"),
            Length(min=3, max=20, message="아이디는 2~20자리 사이여야 합니다"),
        ],
    )
    password1 = PasswordField(
        "비밀번호",
        validators=[
            DataRequired("비밀번호 필수입력"),
            EqualTo("password2", "비밀번호가 일치하지 않습니다"),
        ],
    )
    password2 = PasswordField(
        "비밀번호 확인", validators=[DataRequired("비밀번호 필수입력")]
    )
    email = EmailField(
        "이메일",
        validators=[DataRequired("이메일 필수입력"), Email("이메일 형식 확인")],
    )

bookapp/book/__init__.py
# __init__.py : 해당 디렉토리가 패키지의 일부임을 알려주는 역할

from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db = SQLAlchemy()
migrate = Migrate()


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # ORM
    db.init_app(app)
    migrate.init_app(app, db)
    from . import models

    # 블루프린트 등록
    from .views import main_views, book_views, auth_views

    app.register_blueprint(main_views.bp)
    app.register_blueprint(book_views.bp)
    app.register_blueprint(auth_views.bp)

    return app

bookapp/book/views/auth_views.py
from flask import Blueprint, redirect, url_for, render_template
from book.forms import UserForm


bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/signup", methoeds=["GET", "POST"])
def signup():
    form = UserForm()
    return render_template("auth/signup.html")

bookapp/book/views/book_views.py
from flask import Blueprint, redirect, url_for, render_template, request
from book.models import Book
from book.forms import BookForm
from book import db
from datetime import datetime

# Blueprint("펼칭", 실행되는 모듈명가져오기, url_prefix="/")
bp = Blueprint("book", __name__, url_prefix="/book")


@bp.route("/list/")
def list():
    # 페이지 나누기
    # ?page=2
    page = request.args.get("page", type=int, default=1)

    books = Book.query.order_by(Book.code.desc())
    books = books.paginate(page=page, per_page=10)

    return render_template("book/list.html", books=books)


@bp.route("/remove/<int:code>/")
def remove(code):
    book = Book.query.get_or_404(code)
    db.session.delete(book)
    db.session.commit()
    return redirect(url_for("book.list"))


@bp.route("/delete/<int:code>/")
def delete(code):
    book = Book.query.get_or_404(code)
    return render_template("book/detail.html", book=book)


@bp.route("/edit/<int:code>/", methods=["GET", "POST"])
def edit(code):
    book = Book.query.get_or_404(code)

    if request.method == "POST":
        form = BookForm()
        if form.validate_on_submit():
            form.populate_obj(book)
            db.session.commit()
            return redirect(url_for("book.detail", code=code))
    else:
        # form 과 book 연결
        form = BookForm(obj=book)

    return render_template("book/edit.html", form=form)


@bp.route("/create/", methods=["GET", "POST"])
def create():

    form = BookForm()
    if request.method == "POST":
        if form.validate_on_submit():
            book = Book(
                title=form.title.data,
                author=form.author.data,
                price=form.price.data,
                description=form.description.data,
                created=datetime.now(),
            )
            db.session.add(book)
            db.session.commit()
            return redirect(url_for("book.list"))

    return render_template("book/create.html", form=form)

bookapp/book/views/main_views.py
from flask import Blueprint, redirect, url_for

# Blueprint("펼칭", 실행되는 모듈명가져오기, url_prefix="/")
bp = Blueprint("main", __name__, url_prefix="/")


@bp.route("/")
def index():
    return redirect(url_for("book.list"))

bookapp/book/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
      crossorigin="anonymous"
    />
    <title>Document</title>
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container mt-5">{% block content %}{% endblock %}</div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

bookapp/book/templates/book/create.html
{% extends "base.html" %} {% block content %}

<form method="post">
  {% include "errors.html" %} {{form.csrf_token}}
  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" id="title" value="{{form.title.data or ''}}" name="title" />
  </div>
  <div class="mb-3">
    <label for="author" class="form-label">Author</label>
    <input type="text" class="form-control" id="author" a value="{{form.author.data or ''}}" name="author" />
  </div>
  <div class="mb-3">
    <label for="price" class="form-label">Price</label>
    <input type="text" class="form-control" id="price" a value="{{form.price.data or ''}}" name="price" />
  </div>
  <div class="mb-3">
    <label for="description" class="form-label">Description</label>
    <textarea name="description" id="description" rows="10" class="form-control">
{{form.description.data or ''}}</textarea
    >
  </div>
  <button type="submit" class="btn btn-success">추가</button>
  <a href="{{ url_for('book.list') }}" class="btn btn-primary">목록</a>
</form>
{% endblock %}

bookapp/book/templates/book/detail.html
{% extends "base.html" %} {% block content %}

<form>
  <div class="mb-3">
    <label for="code" class="form-label">Code</label>
    <input type="text" class="form-control" id="code" value="{{book.code}}" readonly name="code" />
  </div>
  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" id="title" value="{{book.title}}" readonly name="title" />
  </div>
  <div class="mb-3">
    <label for="author" class="form-label">Author</label>
    <input type="text" class="form-control" id="author" a value="{{book.author}}" readonly name="author" />
  </div>
  <div class="mb-3">
    <label for="price" class="form-label">Price</label>
    <input type="text" class="form-control" id="price" a value="{{book.price}}" readonly name="price" />
  </div>
  <div class="mb-3">
    <label for="description" class="form-label">Description</label>
    <textarea name="description" id="description" rows="10" class="form-control" readonly>
{{book.description or ''}}</textarea
    >
  </div>
  <a href="{{ url_for('book.edit', code=book.code) }}" class="btn btn-primary">수정</a>
  <a href="{{ url_for('book.list') }}" class="btn btn-primary">목록</a>
</form>
{% endblock %}

bookapp/book/templates/book/edit.html
{% extends "base.html" %} {% block content %}

<form method="post">
  {% include "errors.html" %} {{form.csrf_token}}
  <div class="mb-3">
    <label for="code" class="form-label">Code</label>
    <input type="text" class="form-control" id="code" value="{{form.code.data}}" readonly name="code" />
  </div>
  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" id="title" value="{{form.title.data}}" readonly name="title" />
  </div>
  <div class="mb-3">
    <label for="author" class="form-label">Author</label>
    <input type="text" class="form-control" id="author" a value="{{form.author.data}}" readonly name="author" />
  </div>
  <div class="mb-3">
    <label for="price" class="form-label">Price</label>
    <input type="text" class="form-control" id="price" a value="{{form.price.data}}" name="price" />
  </div>
  <div class="mb-3">
    <label for="description" class="form-label">Description</label>
    <textarea name="description" id="description" rows="10" class="form-control">
{{form.description.data or ''}}</textarea
    >
  </div>
  <button type="submit" class="btn btn-success">수정</button>
  <a class="btn btn-danger" href="{{ url_for('book.remove', code=form.code.data) }}">삭제</a>
  <a href="{{ url_for('book.list') }}" class="btn btn-primary">목록</a>
</form>
{% endblock %}

bookapp/book/templates/book/list.html
{% extends "base.html" %} {% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">code</th>
      <th scope="col">title</th>
      <th scope="col">author</th>
      <th scope="col">price</th>
    </tr>
  </thead>
  <tbody>
    {% for book in books %}
    <tr>
      <th scope="row">{{book.code}}</th>
      <td><a href="{{ url_for('book.list', code=book.code) }}">{{book.title}}</a></td>
      <td>{{book.author}}</td>
      <td>@{{book.price}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<nav>
  <ul class="pagination justify-content-center">
    {% if books.has_prev %}
    <li class="page-item"><a href="?page={{books.prev_num}}" class="page-link">Prev</a></li>

    {% endif %} {% for page_num in books.iter_pages() %} {% if page_num %}
    <li class="page-item {% if page_num == books.page %} active {% endif %}">
      <a class="page-link" href="?page={{page_num}}" aria-current="page">{{page_num}}</a>
    </li>
    {% else %}
    <li class="disabled"><a class="page-link" href="javascript:void(0)">...</a></li>
    {% endif %} {% endfor %} {% if books.has_next %}
    <li class="page-item"><a class="page-link" href="?page{{books.next_num}}">Next</a></li>
    {% endif %}
  </ul>
</nav>
{% endblock %}

bookapp/book/templates/errors.html
{% if form.errors %}
<div class="alert alert-danger">
  {% for field, errors in form.errors.item() %}
  <strong>{{ form[field].label }}</strong>
  <ul>
    {% for error in errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
  {% endfor %}
</div>
{% endif %}

bookapp/book/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">BookApp</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">로그아웃</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">로그인</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('book.create')}}">도서입력</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>