tutorial/todo/models.py
# Entity

from todo import db
from sqlalchemy import text


class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), nullable=False)  # text
    description = db.Column(db.Text(), nullable=False)  # textarea
    created = db.Column(db.DateTime(), nullable=False)
    # default = False (flask app 실행)
    # server_default=text("false") : 테이블 생성 구문에 추가
    completed = db.Column(db.Boolean(), default=False, server_default=text("false"))
    important = db.Column(db.Boolean(), default=False, server_default=text("false"))

tutorial/todo/forms.py
# Entity

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField
from wtforms.validators import DataRequired


# == DTO 역할
class TodoForm(FlaskForm):
    title = StringField(validators=[DataRequired("제목 필수 입력")])  # text
    description = TextAreaField(validators=[DataRequired("상세 필수 입력")])  # textarea
    completed = BooleanField()
    important = BooleanField()

tutorial/todo/views/main_views.py
from flask import Blueprint, redirect, url_for

# Blueprint("별칭", 실행되는 모듈명 가져오기, url_prefix="/")
bp = Blueprint("main", __name__, url_prefix="/")


@bp.route("/")
def index():
    # url 지정할 때 사용하는 함수
    # 주소를 지정하진 않고 별칭을 넣음
    return redirect(url_for("todo.list"))

tutorial/todo/views/todo_views.py
from flask import Blueprint, render_template, request, redirect, url_for
from todo.models import Todo
from todo.forms import TodoForm
from datetime import datetime
from todo import db

# Blueprint("별칭", 실행되는 모듈명 가져오기, url_prefix="/")
bp = Blueprint("todo", __name__, url_prefix="/todo")


@bp.route("/list/")
def list():
    todos = Todo.query.filter(Todo.completed == 0).order_by(Todo.id.desc())
    return render_template("todo/todo_list.html", todos=todos)


@bp.route("/done/list/")
def done_list():
    todos = Todo.query.filter(Todo.completed == 1).order_by(Todo.id.desc())
    return render_template("todo/done_list.html", todos=todos)


@bp.route("/edit/<int:id>/", methods=["GET", "POST"])
def edit(id):
    todo = Todo.query.get_or_404(id)

    if request.method == "POST":
        form = TodoForm()
        if form.validate_on_submit():
            form.populate_obj(todo)  # 원본 todo 과 form 에 담긴 변경된 todo 비교
            db.session.commit()  # 달라진 부분만 담아서 전송
            return redirect(url_for("todo.detail", id=id))
    else:
        form = TodoForm(obj=todo)

    return render_template("todo/todo_edit.html", form=form)


@bp.route("/detail/<int:id>/")
def detail(id):
    todo = Todo.query.get_or_404(id)
    return render_template("todo/todo_detail.html", todo=todo)


@bp.route("/register/", methods=["GET", "POST"])
def register():
    form = TodoForm()
    if request.method == "POST" and form.validate_on_submit():
        todo = Todo(
            title=form.title.data,
            description=form.description.data,
            important=form.important.data,
            created=datetime.now(),
        )
        db.session.add(todo)
        db.session.commit()
        return redirect(url_for("main.index"))  # == todo.list

    return render_template("todo/todo_create.html", form=form)


@bp.route("/done/<int:id>/")
def done(id):
    todo = Todo.query.get_or_404(id)
    todo.completed = True
    db.session.commit()
    return redirect(url_for("todo.detail", id=todo.id))

tutorial/todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
      crossorigin="anonymous"
    />
    <title>Document</title>
  </head>
  <body>
    <div class="container mt-5">{% block content %}{% endblock %}</div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

tutorial/todo/templates/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Create</h1>
    <form action="" method="post">
      <div>
        <input type="text" name="name" />
        <input type="submit" value="전송" />
      </div>
    </form>
  </body>
</html>

tutorial/todo/templates/todo/done_list.html
{% extends "base.html" %} {% block content %}
<div class="row mb-3">
  <h1>완료 목록</h1>
</div>
<div class="row mb-3">
  <div class="col">
    <a href="{{ url_for('todo.register') }}">Todo 추가</a>
  </div>
  <div class="col text-end">
    <a href="{{ url_for('todo.list') }}" class="btn btn-primary">미완료 Todo</a>
  </div>
</div>
<table class="table">
  <tbody>
    {% for todo in todos %}
    <tr>
      <th scope="row">
        <a href="{{ url_for('todo.detail', id=todo.id) }}">{{todo.title}}</a>
        {% if todo.important %}
        <span class="badge bg-danger">!</span>
        {% endif %}
      </th>
      <td>
        <a href="{{ url_for('todo.done', id=todo.id) }}" class="btn btn-danger btn-sm">완료</a>
        <a href="" class="btn btn-primary btn-sm">수정</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

tutorial/todo/templates/todo/todo_create.html
{% extends "base.html" %} {% block content %}
<div class="row mb-3">
  <h1>Todo 추가</h1>
</div>
<form method="post">
  {% include "errors.html" %} {{form.csrf_token}}
  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" id="title" aria-describedby="title" name="title" />
  </div>
  <div class="mb-3">
    <label for="description" class="form-label">Description</label>
    <textarea name="description" id="description" rows="10" class="form-control"></textarea>
  </div>

  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="important" name="important" />
    <label class="form-check-label" for="important">Important</label>
  </div>
  <button type="submit" class="btn btn-success">추가</button>
  <a href="{{ url_for('todo.list') }}" class="btn btn-primary">목록</a>
</form>
{% endblock %}

tutorial/todo/templates/todo/todo_detail.html
{% extends "base.html" %} {% block content %}
<div class="row mb-3">
  <h1>Todo 상세</h1>
</div>
<form>
  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" id="title" aria-describedby="title" value="{{todo.title}}" readonly />
  </div>
  <div class="mb-3">
    <label for="description" class="form-label">Description</label>
    <textarea name="description" id="description" rows="10" class="form-control" readonly>
{{todo.description}}</textarea
    >
  </div>
  <div class="mb-3 form-check">
    <input
      type="checkbox"
      class="form-check-input"
      id="completed"
      name="completed"
      {%
      if
      todo.completed
      %}
      checked
      {%
      endif
      %}
    />
    <label class="form-check-label" for="completed">Completed</label>
  </div>
  <div class="mb-3 form-check">
    <input
      type="checkbox"
      class="form-check-input"
      id="important"
      name="important"
      {%
      if
      todo.important
      %}
      checked
      {%
      endif
      %}
    />
    <label class="form-check-label" for="important">Important</label>
  </div>
  <a href="{{ url_for('todo.list') }}" class="btn btn-primary">목록</a>
</form>
{% endblock %}

tutorial/todo/templates/todo/todo_edit.html
{% extends "base.html" %} {% block content %}
<div class="row mb-3">
  <h1>Todo 수정</h1>
</div>
<form method="post">
  {% include "errors.html" %} {{form.csrf_token}}
  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" id="title" name="title" value="{{form.title.data}}" />
  </div>
  <div class="mb-3">
    <label for="description" class="form-label">Description</label>
    <textarea name="description" id="description" rows="10" class="form-control">{{form.description.data}}</textarea>
  </div>
  <div class="mb-3 form-check">
    <input
      type="checkbox"
      class="form-check-input"
      id="completed"
      name="completed"
      {%
      if
      form.completed.data
      %}
      checked
      {%
      endif
      %}
    />
    <label class="form-check-label" for="completed">Completed</label>
  </div>
  <div class="mb-3 form-check">
    <input
      type="checkbox"
      class="form-check-input"
      id="important"
      name="important"
      {%
      if
      form.important.data
      %}
      checked
      {%
      endif
      %}
    />
    <label class="form-check-label" for="important">Important</label>
  </div>
  <button type="submit" class="btn btn-success">수정</button>
  <a href="{{ url_for('todo.list') }}" class="btn btn-primary">목록</a>
</form>
{% endblock %}

tutorial/todo/templates/todo/todo_list.html
{% extends "base.html" %} {% block content %}
<div class="row mb-3">
  <h1>목록</h1>
</div>
<div class="row mb-3">
  <div class="col">
    <a href="{{ url_for('todo.register') }}">Todo 추가</a>
  </div>
  <div class="col text-end">
    <a href="{{ url_for('todo.done_list') }}" class="btn btn-primary">완료 Todo</a>
  </div>
</div>
<table class="table">
  <tbody>
    {% for todo in todos %}
    <tr>
      <th scope="row">
        <a href="{{ url_for('todo.detail', id=todo.id) }}">{{todo.title}}</a>
        {% if todo.important %}
        <span class="badge bg-danger">!</span>
        {% endif %}
      </th>
      <td>
        <a href="{{ url_for('todo.done', id=todo.id) }}" class="btn btn-danger btn-sm">완료</a>
        <a href="{{ url_for('todo.edit', id=todo.id) }}" class="btn btn-primary btn-sm">수정</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}